language: ruby
sudo: false

rvm:
  - 2.3.1

matrix:
  include:
    - rvm: 2.3.1
      env: "RAILS_VERSION=4.2.5"
    - rvm: 2.2.5
      env: "RAILS_VERSION=4.2.5"

before_install:
- gem install -v '4.2.5' rails
- rails _4.2.5_ new -s .
- rake findit:install
