language: ruby
sudo: false

rvm:
  - 2.3.1

matrix:
  include:
    - rvm: 2.3.1
      env: "RAILS_VERSION=4.2.6"
    - rvm: 2.2.5
      env: "RAILS_VERSION=5.0.0"

before_install:
- gem install bundler
