# Possible values for "api" are eds or worldcat
# 
# If you select eds as your api, it will attempt IP authentication
# if you do not add the username and password variables
# 
# If you select worldcat as your api, you will need to provide
# an api_key and an api_key_secret

production:
    environment: production
    api: eds
development:
    environment: development
    api: eds
    username: api_user
    password: my_password
test:
    environment: test
    api: worldcat
    api_key: 1234
    api_key_secret: 567890
